### ISSUE TITLE
Mac Os Can't activate VPN mode

### ISSUE THREAD

**Issue by miladerakhshan** [abbasnaqdi/nekoray-macos#2]
Hello. I hope you are doin well. i cannot activate VPN mode any longer. it worked perfectly and idk what's happened. I have Macbook Air M1 2020. Will you please help me with that ?

**Comment by aaaamirabbas** [comment]
Hi, I am aware of the problem of VPN and this problem has long been in the NekoRay project.

**The problem is that the main NekoRay developers team has put the macOS version out of priority instead of solving the problem (so you are currently a new version of NekoRay from this You download the repository).**

However, the VPN mode in NekoRay is not going to work well, but you can change the VPN settings, for example, **set the VPN implementation to the `gVisor`**, it will probably work or try other settings.

But even if the VPN mode is activated, you will have over -use of **`CPU`** sources.

Now, this is the best thing that is available.
So use the **‍`proxy mode`** for now and let's hope that things will get better in the future.

**Comment by amerllica** [comment]
@miladerakhshan 

I had the same problem with this repo's version. I just turned back the version to 2.12 from the main Github repo. and everything works like a charm again.

**Comment by amerllica** [comment]
@abbasnaqdi , @miladerakhshan 

Live this repo, and download FoXray on your macOS. it has got everything without any issues or problems. Even reality is supported by FoXray. Also, FoXray supports all Apple platforms and architectures.
