### ISSUE TITLE
3.24 任然奔溃

### ISSUE THREAD

**Issue by heibailiangxiangwang20** [abbasnaqdi/nekoray-macos#43]
3.24 amd和arm任然奔溃

**Comment by heibailiangxiangwang20** [comment]
3.24版本，我尝试把 \Contents\Frameworks\libfreetype.6.dylib
替换成3.18版本里面的libfreetype.6.dylib
运行成功

**Comment by abbasnaqdi** [comment]
**Please run the application like this in the terminal and send me the crash log:**
./nekoray_amd64.app/Contents/MacOS/nekoray
Or
./nekoray_arm64.app/Contents/MacOS/nekoray

**Comment by meower1** [comment]
> **Please run the application like this in the terminal and send me the crash log:** `./nekoray_amd64.app/Contents/MacOS/nekoray` Or `./nekoray_arm64.app/Contents/MacOS/nekoray`

/Applications/nekoray_arm64.app/Contents/MacOS/nekoray                    ─╯
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa.

[1]    19849 abort      /Applications/nekoray_arm64.app/Contents/MacOS/nekoray

**Comment by meower1** [comment]
> In version 3.24, I tried to replace \Contents\Frameworks\libfreetype.6.dylib with libfreetype.6.dylib in version 3.18 and it ran successfully.

This fixed it for me as well on arm <3
